<?php

function filter_woocommerce_new_customer_data( $args ) {

    if (is_checkout()){

        if(isset($_COOKIE['is_older']) && !empty($_COOKIE['is_older'])){
            $args['role'] = 'student';
        }else{
            $args['role'] = 'parent';
        }
    }

    return $args;
}

add_filter( 'woocommerce_new_customer_data', 'filter_woocommerce_new_customer_data', 10, 1 );



add_action('woocommerce_order_status_changed', 'crear_y_loguear_usuario_si_pago_exitoso_optimizado', 9, 4);
function crear_y_loguear_usuario_si_pago_exitoso_optimizado($order_id, $old_status, $new_status, $order) {
    $valid_statuses = ['on-hold', 'processing', 'completed'];

    // Exit if the new status is not one of the valid statuses
    if (!in_array($new_status, $valid_statuses)) {
        return;
    }

    $email = $order->get_billing_email();

    // Set student_id on order from cookie if it's for a fee
    if (isset($_COOKIE['fee_student_id']) && !empty($_COOKIE['fee_student_id'])) {
        if (!$order->meta_exists('student_id')) {
            $order->update_meta_data('student_id', sanitize_text_field(wp_unslash($_COOKIE['fee_student_id'])));
            $order->save();
        }
    }

    // Exit if user already exists
    if (email_exists($email)) {
        return;
    }

    $first_name = $order->get_billing_first_name();
    $last_name = $order->get_billing_last_name();
    $username = sanitize_user(current(explode('@', $email)), true);
    $password = wp_generate_password(); // Strong password generated by WordPress

    $user_id = wp_create_user($username, $password, $email);

    // Handle user creation errors
    if (is_wp_error($user_id)) {
        // Log the error for debugging purposes
        error_log('Error creating user for order ' . $order_id . ': ' . $user_id->get_error_message());
        return;
    }

    // Update basic user information
    wp_update_user([
        'ID'         => $user_id,
        'first_name' => $first_name,
        'last_name'  => $last_name,
    ]);

    // Assign 'parent' role
    $user = new WP_User($user_id);
    $user->set_role('parent');

    // Set the newly created user as the customer for the order and save
    $order->set_customer_id($user_id);
    $order->save();

    // --- Update User Metadata from Order and Cookies ---

    // Default status_register if not set
    if (!get_user_meta($user_id, 'status_register', true)) {
        update_user_meta($user_id, 'status_register', 0);
    }

    // Billing details from order
    update_user_meta($user_id, 'billing_country', $order->get_billing_country());
    update_user_meta($user_id, 'billing_city', $order->get_billing_city());
    update_user_meta($user_id, 'billing_postcode', $order->get_billing_postcode());
    update_user_meta($user_id, 'billing_phone', $order->get_billing_phone());
    update_user_meta($user_id, 'billing_address_1', $order->get_billing_address_1());

    // User metadata from cookies (grouped for readability)
    $cookie_meta_map = [
        'id_document_parent'   => 'id_document',
        'parent_document_type' => 'type_document',
        'birth_date_parent'    => 'birth_date',
        'gender_parent'        => 'gender',
        'ethnicity_parent'     => 'ethnicity',
    ];

    foreach ($cookie_meta_map as $cookie_key => $meta_key) {
        if (isset($_COOKIE[$cookie_key]) && !empty($_COOKIE[$cookie_key])) {
            update_user_meta($user_id, $meta_key, sanitize_text_field(wp_unslash($_COOKIE[$cookie_key])));
        }
    }

    // Handle student-related operations if all necessary cookies are present
    $required_student_cookies = [
        'name_student', 'last_name_student', 'birth_date', 'initial_grade',
        'program_id', 'email_partner', 'number_partner'
    ];

    $all_student_cookies_set = true;
    foreach ($required_student_cookies as $cookie) {
        if (!isset($_COOKIE[$cookie]) || empty($_COOKIE[$cookie])) {
            $all_student_cookies_set = false;
            break;
        }
    }

    if ($all_student_cookies_set) {
        $student_id = insert_student($user_id); // Assuming this function exists and works
        insert_register_documents($student_id, sanitize_text_field(wp_unslash($_COOKIE['initial_grade']))); // Assuming this function exists and works

        if (!$order->meta_exists('student_id')) {
            $order->update_meta_data('student_id', $student_id);
        }

        if (isset($_COOKIE['id_bitrix']) && !empty($_COOKIE['id_bitrix'])) {
            $order->update_meta_data('id_bitrix', sanitize_text_field(wp_unslash($_COOKIE['id_bitrix'])));
        }
        $order->save();

        // Trigger new applicant email
        $email_new_student = WC()->mailer()->get_emails()['WC_New_Applicant_Email'];
        if ($email_new_student) {
            $email_new_student->trigger($student_id);
        }

        insert_data_student($order); // Assuming this function exists and works

        if (isset($_COOKIE['is_scholarship']) && !empty($_COOKIE['is_scholarship'])) {
            save_scholarship(); // Assuming this function exists and works
        }
    }

    // Add 'parent' role if 'is_older' cookie is set (redundant if already set above, but good for safety)
    if (isset($_COOKIE['is_older']) && !empty($_COOKIE['is_older'])) {
        // add_role_user($user_id, 'parent'); // Assuming this function exists, but user already set to 'parent' role above
    }

    // Update password if 'password' cookie is set
    if (isset($_COOKIE['password']) && !empty($_COOKIE['password'])) {
        wp_update_user([
            'ID'        => $user_id,
            'user_pass' => sanitize_text_field(wp_unslash($_COOKIE['password'])),
        ]);
        // Note: 'user_pass_reset' => 1 is usually for forcing a password reset on next login, not for directly setting.
        // If the intention is to set the password and prevent a reset, remove 'user_pass_reset'.
    }

    set_institute_in_order($order); // Assuming this function exists and works

    // Log the user in automatically
    wp_set_current_user($user_id);
    wp_set_auth_cookie($user_id, true); // true = persistent session

    /* If you want to redirect the user after successful login, uncomment the following:
    wp_redirect(get_permalink(get_option('woocommerce_myaccount_page_id')) . '/orders');
    exit;
    */
}

function checkout_set_customer_id( $current_user_id ) { 
	if(!$current_user_id ){
		$user = get_user_by('email', $_POST['billing_email']);
		if ($user){
			$current_user_id = $user->ID;
		}
	}
	return $current_user_id;
} 

add_filter('woocommerce_checkout_customer_id', 'checkout_set_customer_id');

function save_account_details( $user_id ) {

    global $current_user;
    $roles = $current_user->roles;

    if( in_array('parent',$roles) && !in_array('student',$roles) ){


        if(isset( $_POST['billing_city']) && !empty($_POST['billing_city'])){
            update_user_meta( $user_id,'billing_city',sanitize_text_field($_POST['billing_city']));
        }

        if(isset( $_POST['billing_country']) && !empty($_POST['billing_country'])){
            update_user_meta( $user_id,'billing_country',sanitize_text_field( $_POST['billing_country']));
        }

        if(isset( $_POST['number_phone_hidden']) && !empty($_POST['number_phone_hidden'])){
            update_user_meta( $user_id,'billing_phone',sanitize_text_field( $_POST['number_phone_hidden']));
        }

        if(isset( $_POST['gender']) && !empty($_POST['gender'])){
            update_user_meta( $user_id,'gender',sanitize_text_field( $_POST['gender']));
        }

        if(isset( $_POST['id_document']) && !empty($_POST['id_document'])){
            update_user_meta( $user_id,'id_document',sanitize_text_field( $_POST['id_document']));
        }

        if(isset( $_POST['birth_date']) && !empty($_POST['birth_date'])){
            update_user_meta( $user_id,'birth_date',sanitize_text_field( $_POST['birth_date']));
        }

        if(isset( $_POST['document_type']) && !empty($_POST['document_type'])){
            update_user_meta( $user_id,'document_type',sanitize_text_field( $_POST['document_type']));
            update_user_meta( $user_id,'type_document',sanitize_text_field( $_POST['type_document']));
        }

        if(isset( $_POST['billing_postcode']) && !empty($_POST['billing_postcode'])){
            update_user_meta( $user_id,'billing_postcode',sanitize_text_field( $_POST['billing_postcode']));
        }

        if(isset( $_POST['occupation']) && !empty($_POST['occupation'])){
            update_user_meta( $user_id,'occupation',sanitize_text_field( $_POST['occupation']));
        }
    }
}

add_action( 'woocommerce_save_account_details', 'save_account_details' );

function validated_account_details_required_fields( $required_fields ){ 
    
    global $current_user;
    $roles = $current_user->roles;

    if(in_array('parent',$roles) && !in_array('student',$roles)){

        $required_fields['billing_city'] = __('Billing city','edusystem');
        $required_fields['billing_country'] = __('Billing country','edusystem');
        $required_fields['number_phone_account'] = __('Number phone','edusystem');
        $required_fields['gender'] = __('Gender','edusystem');
        $required_fields['birth_date'] = __('Birth Date','edusystem');
        $required_fields['id_document'] = __('ID Document','edusystem');
        $required_fields['document_type'] = __('Type document','edusystem');
        $required_fields['billing_postcode'] = __('Post Code','edusystem');
        $required_fields['occupation'] = __('Occupation','edusystem');

    }

    return $required_fields;
}

add_filter('woocommerce_save_account_details_required_fields', 'validated_account_details_required_fields');

function is_password_user_moodle($student_id){

    global $wpdb;
    $table_students = $wpdb->prefix.'students';

    $data_student = $wpdb->get_row("SELECT * FROM {$table_students} WHERE id={$student_id}");

    if($data_student){

        if(!empty($data_student->moodle_password)){
            return true;
        }
    }

    return false;
}

function generate_password_user(){
    $password = wp_generate_password(12);
    return $password;
}

function add_role_user($user_id,$role){

    $user = new WP_User($user_id);

    if($user){
        $user->add_role($role);
    }
}
